logging:
  level:
    org.springframework: info

spring:
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: ${DB_URL}
      auto-commit: false
      driver-class-name: org.postgresql.Driver
  liquibase:
    user: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    change-log: classpath:db/changelog/changelog-master.yaml
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    enabled: true
  modulith:
    events:
      republish-outstanding-events-on-restart: true
      completion-mode: archive
