logging:
  level:
    org.springframework: info

spring:
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: ${DB_URL}
      auto-commit: false
      driver-class-name: org.postgresql.Driver
      pool-name: HikariPool
      maximum-pool-size: 20
      minimum-idle: 10
      max-lifetime: 1800000
      idle-timeout: 300000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 2000
  liquibase:
    user: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    change-log: classpath:db/changelog/changelog-master.yaml
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    enabled: true
  modulith:
    events:
      republish-outstanding-events-on-restart: true
      completion-mode: archive
  main:
    lazy-initialization: true
  docker:
    compose:
      lifecycle-management: start_and_stop
